let firstQ=prompt("welcome in the website,great website for websiting processing,if you want to continue type any thing")
alert("so you type what you type , you are genius,")
console.log('Typing question=',firstQ)
let secondQ=prompt("ok now type number bigger than 1 and less than 3")
alert("its 2")
console.log('hard qeustion=',secondQ)
let thirdQ=prompt("now am the genius XD,  the next part is to type your favorite color")
alert("its red ,easy peasy lemon squeezy")
console.log('coler question=',thirdQ)
let forthQ=prompt("You have reached the final boss ohh i mean part, what is the sluotion for (2x=2)? think carfully its hard one , you have 2 days to answer ")
alert("if your answer equal to 1 go to my cola website and order cole ,its gonna be on the house ")
console.log('math question=',firstQ)